BARNEYMAN_HOST = "host"
BARNEYMAN_HOSTNAME = "hostname"
BARNEYMAN_CONFIG_ENTRY = "barneyman"
BARNEYMAN_DEVICES = "Devices"
BARNEYMAN_DEVICES_SEEN = "DevicesSeen"

MDNS_HOSTNAME = BARNEYMAN_HOSTNAME

DEVICES_LIGHT = "light"
DEVICES_SENSOR = "sensor"
DEVICES_CAMERA = "camera"

LISTENING_PORT = "listeningport"

AUTH_TOKEN = "authtoken"

