BARNEYMAN_HOST = "host"
BARNEYMAN_HOSTNAME = "hostname"
BARNEYMAN_CONFIG_ENTRY = "barneyman"
BARNEYMAN_DOMAIN = BARNEYMAN_CONFIG_ENTRY
BARNEYMAN_SERVICES = "_" + BARNEYMAN_DOMAIN + "._tcp.local."
BARNEYMAN_DEVICES = "Devices"
BARNEYMAN_DEVICES_SEEN = "DevicesSeen"
BARNEYMAN_BROWSER = "browser"

MDNS_HOSTNAME = BARNEYMAN_HOSTNAME

SIGNAL_BARNEYMAN_DISCOVERED = "barneyman_device_discovered"
SIGNAL_AUTHTOKEN_CHANGED = "barneyman_new_auth"

DEVICES_LIGHT = "light"
DEVICES_SENSOR = "sensor"
DEVICES_CAMERA = "camera"

LISTENING_PORT = "listeningport"

AUTH_TOKEN = "authtoken"

BARNEYMAN_USER_ID = "barneyman_user_id"
BARNEYMAN_USER = BARNEYMAN_DOMAIN + "_user"
BARNEYMAN_ANNOUNCE_CLIENT = "device state announce"
BARNEYMAN_ID = "instanceid"
